### ISSUE TITLE
Error when there is no user link on a Q&A

### ISSUE THREAD

**Issue by sduenas** [MetricsGrimoire/Sibyl#18]
This [Q&A] (https://ask.openstack.org/en/question/57932/why-do-i-need-to-provide-contact-information-when-signing-the-cla/) does not have any author, so it makes Sibyl to raise an exception.

```
Analyzing: https://ask.openstack.org/en/question/57932/why-do-i-need-to-provide-contact-information-when-signing-the-cla/
    * Question not found in db
2015-01-29 16:47:56,480 Starting new HTTPS connection (1): ask.openstack.org
/home/sduenas/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py:324: Warning: Out of range value for column 'added_at' at row 1
  cursor.execute(statement, parameters)
Traceback (most recent call last):
  File "/home/sduenas/.local/bin/sibyl.py", line 182, in <module>
    askbot_parser(session, opts.url)
  File "/home/sduenas/.local/bin/sibyl.py", line 128, in askbot_parser
    answers = askbot.answers(dbquestion)
  File "/home/sduenas/.local/lib/python2.7/site-packages/pysibyl/askbot.py", line 224, in answers
    return self.questionHTML.getAnswers(dbquestion.question_identifier) 
  File "/home/sduenas/.local/lib/python2.7/site-packages/pysibyl/askbot.py", line 342, in getAnswers
    user_links = user[0].findAll('a')
IndexError: list index out of range
```

**Comment by acs** [comment]
Yes, but the parsing process so continue with the rest. No?

**Comment by sduenas** [comment]
What do you mean? When this exception is raised the parsing process does not continue. Sibyl crashes.

**Comment by acs** [comment]
I propose that the exception is caught, reported but that the parsing process continue and sibyl should not crash.
